name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    #container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py  # generate plot.png
          
          # Create CML report
          echo "## MODEL METRICS" >> report.md
          cat metrics.txt >> report.md

          echo "## Data Viz" >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md
          cml-send-comment report.md
          
          # cml-publish embeds the png as a markdown image in the report.md
          # -- md indicates that img should be formatted in Markdown
          
          #echo '![](./plot.png "Confusion Matrix")' >> report.md
          #cml comment create report.md
